### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by drsect0r** [docker-php/docker-php#159]
When exceptions are thrown provide better feedback messages what exactly is happening. This could also be solved with some sort of validator mechanism.

**Comment by joelwurtz** [comment]
Good idea, PRs are welcome !

**Comment by Babacooll** [comment]
Hi I'd like to contribute on this one, but could you be more specific about "validator mechanism" ? I'm not sure I understand what you mean. Thanks !

**Comment by drsect0r** [comment]
@Babacooll I meant with validator mechanism that user input is validated before being send to the Docker API.

**Comment by joelwurtz** [comment]
Docker PHP now throws exception from Docker API, still no validator on client side, but this is a start. Validation is something planned for Jane PHP (but not done ATM), and docker php will directly profit from it when it will be available.

Closing this ATM
