### ISSUE TITLE
Example of how to send command to container

### ISSUE THREAD

**Issue by drsect0r** [docker-php/docker-php#162]
After reading the documentation and examining the issues. I'm looking for an example how I can send a command to a container, execute it and retrieve the output of that command. 

**Update:**
I have the above working using the documentation located here: (http://docker-php.readthedocs.org/en/latest/cookbook/container-run/) but only when I specify a shell in setCmd(). How can I connect to an already running instance opening a shell and run some commands? 

How can i active the equivalent of; `docker exec --interactive=true --tty=true --user=www-data container /bin/bash` where `--user=www-data` is considered a nice to have.

**Comment by joelwurtz** [comment]
http://docker-php.readthedocs.org/en/latest/cookbook/container-run/ isn't enough, what do you think it's missing ?

**Comment by drsect0r** [comment]
@joelwurtz I just updated my original question.

**Comment by drsect0r** [comment]
@joelwurtz essentialy how can

**Comment by joelwurtz** [comment]
You need to use the ExecManager, which provides endpoint to exec a process in a existing container, api is similar to the one in ContainerManager.

**Comment by drsect0r** [comment]
@joelwurtz I will have a look around and report back :+1:

**Comment by drsect0r** [comment]
@joelwurtz I found the test cases and I have it working with the following example. I fail to see how I can use this to send commands in bash and see the output. Could you provide an example?

``` php 
$execManager = $this->docker->getExecManager();

$execConfig = new ExecConfig();
$execConfig->setAttachStdout(true);
$execConfig->setAttachStderr(true);
$execConfig->setCmd([
    "echo",
    "asd",
]);

$execCreateResult = $execManager->create($containerCreate->getId(), $execConfig);

$execStartConfig = new ExecStartConfig();
$execStartConfig->setDetach(false);
$execStartConfig->setTty(false);

$stream = $execManager->start($execCreateResult->getId(), $execStartConfig, [], ExecManager::FETCH_STREAM);

$stdoutFull = "";
$stream->onStdout(function ($stdout) use (&$stdoutFull)
{
    $stdoutFull .= $stdout;
});
$stream->wait();
var_dump($stdoutFull);
```
