### ISSUE TITLE
checkAuthentication

### ISSUE THREAD

**Issue by boonkerz** [docker-php/docker-php#169]
i can not login to quay.io

`PHP Catchable fatal error:  Argument 1 passed to Symfony\Component\OptionsResolver\OptionsResolver::resolve() must be of the type array, string given, called in /data/www/vendor/jane/open-api/src/Client/QueryParam.php on line 60 and defined in /data/www/vendor/symfony/options-resolver/OptionsResolver.php on line 744`

**Comment by joelwurtz** [comment]
Can you provide an example of the failing code ?
