### ISSUE TITLE
How to use docker-php?

### ISSUE THREAD

**Issue by Mellnik** [docker-php/docker-php#170]
Downloaded docker-php and did "composer install".
My question is how to include docker-php in my php project.

Sorry for that dumb question but I never used composer before.

Thanks.

**Comment by hxpro** [comment]
1/ install composer [getcomposer.org](https://getcomposer.org/doc/00-intro.md)
2/ require docker-php library `composer require docker-php/docker-php` inside your project folder
3/ include vendor/autoload.php in your php script

**Comment by Mellnik** [comment]
Thanks. So that's what my test php looks like:

```
$client = new Docker\DockerClient([
    'remote_socket' => 'tcp://debianserver:2375',
    'ssl' => false,
]);

$docker = new Docker\Docker($client);

$containers = $docker->getContainerManager()->findAll();
```

My docker daemon is up and 2 containers running. Firewall is disabled.

> /usr/bin/docker daemon -H tcp://0.0.0.0:2375

And that's the output of the php script:

> Array ( ) 

What am I doing wrong?

**Comment by joelwurtz** [comment]
Do you have any container running ?

By default it will only show running containers, if you wish to retrieve all containers you should use the `all` parameters : 

```
$containers = $docker->getContainerManager()->findAll(['all' => true]);
```

**Comment by xrain0610** [comment]
if use the ssl  how to config?
I set it like below:
>$docker_certs_path = storage_path('certs');
	$cafile = $docker_certs_path.DIRECTORY_SEPARATOR.'ca.pem';
    $certfile = $docker_certs_path.DIRECTORY_SEPARATOR.'cert.pem';
    $keyfile = $docker_certs_path.DIRECTORY_SEPARATOR.'key.pem';
    $options['ssl'] = true;
    $options['stream_context_options']['ssl'] = [
        'cafile' => $cafile,
        'local_cert' => $certfile,
        'local_pk' => $keyfile,
        'peer_name' => 'boot2docker',
        ];
    $options['remote_socket'] = 'tcp://192.168.64.7:3376';
    $client = new Docker\DockerClient($options);
    $docker = new Docker\Docker($client);
    $containers = $docker->getContainerManager()->findAll();
    dd($containers);

it doesn't work. help me! thanks!

**Comment by joelwurtz** [comment]
What is the error ?

**Comment by xrain0610** [comment]
@joelwurtz 
can't enable tls

this is my enviroment:
>php-curl php php-pdo php-pdo_mysql php-mcrypt php-openssl php-fpm php-zip php-xml php-xmlrpc php-pear php-sockets php-gettext php-iconv php-sysvsem php-sysvmsg php-pdo_pgsql php-snmp php-shmop php-sysvshm php-pdo_sqlite php-posix php-imap php-zlib php-xsl php-wddx php-intl php-ldap php-pcntl php-exif php-calendar php-ftp php-bz2 php-enchant php-json php-dom php-phar php-ctype php-gd php-bcmath php-bz2 php-memcache php-soap nginx

I use docker container to develope, and see :  https://github.com/simcu/docker-laravel

and  i have a issue #168 ,  both swarm or docekr daemon have the trouble.

**Comment by joelwurtz** [comment]
@Mellnik does it work for you ? I will close this, if you still have a problem don't hesitate to reopen this.
