### ISSUE TITLE
NetworkManager connect needs to set Content-Type

### ISSUE THREAD

**Issue by atroy** [docker-php/docker-php#177]
Hi I am currently facing an issue with the `getNetworkManager()->connect()`-method. This is because the Docker-API requests content-type to be  'application/json'. 

Exact error message:
`Content-Type specified () must be 'application/json'`

At the moment I patched it myself, by adding it to the headers.

**Comment by joelwurtz** [comment]
Thanks for the report will do the change in the schema !

**Comment by joelwurtz** [comment]
Should be good with 1.22.2 and 1.21.3 versions

**Comment by Babacooll** [comment]
Same issue I think for VolumeManager (create action for example). Can you confirm  @joelwurtz ?
