### ISSUE TITLE
how to run commands on existing container

### ISSUE THREAD

**Issue by aarobc** [docker-php/docker-php#178]
So far in all the documentation and tests I'm only seeing ways to run commands on a container if you create it with the appropriate settings, eg:

```
$containerConfig->setImage('busybox:latest')                            
->setOpenStdin(true)                                    
->setTty(true)                                          
->setAttachStdin(true)                                  
->setAttachStdout(true)                                 
->setAttachStderr(true)                                 
```

I'm needing the equivalent of `docker exec` so I can run a command on existing containers. 

Once instructed I'd be happy to help improve the documentation.

**Comment by joelwurtz** [comment]
You should use the ExecManager for that, look at https://github.com/docker-php/docker-php/blob/1.22/generated/Resource/ExecResource.php

**Comment by leasi** [comment]
Hello Joel and aarobc !

I encounter the same issue than aarobc. Here's where I am so far ($docker being a Docker object, and $id the id of the container I want to execute commands on) : 

```
$execconfig = new ExecConfig();
$execconfig->setCmd("ls");
$execmanager = $docker->getExecManager();
$response=$execmanager->create($id,$execconfig);
$statuscode = $response->getStatusCode();
echo $statuscode;
```

I get an Internal Server Response in return.

I'm sure I'm missing key parameters in one or the other functions (or perhaps I did miss a step, which could be very possible). Could anyone provide me a working example I could use ? I don't have high developing skills so it's unfortunately quite difficult for me not to get overwhelmed by exploring the source code...

I'm sure that some quick examples like the ones I'm trying to make work could be a big help to the community, if documentation is not possible at the moment.

Thank you for docker-php which will exactly answer my needs as soon as I master it :)

**Comment by noxify** [comment]
Hi,

i had currently the same problem and your current steps helped me to "solve" my problem.

I was not able to get the response from the console but the command was executed successfully.

As base i'm using a bit modified version from laradock.
Inside my Laravel Workspace i have modifed the `router.php` to the following:

```
<?php

use Docker\Docker;
use Docker\DockerClient;
use Docker\API\Model\ExecConfig;
use Docker\API\Model\ExecStartConfig;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {



	try {
		$client = new DockerClient([
		    'remote_socket' => 'unix:///var/run/docker.sock',
		    'ssl' => false,
		]);
		$docker = new Docker($client);
		//$containerManager = $docker->getContainerManager()->findAll();
		$execconfig = new ExecConfig();
		//$execconfig->setCmd(array('mkdir', '/tmp/hugo2'));
		$execconfig->setCmd(array('echo', '"Hugo was here"'));
		$startConfig = new ExecStartConfig();
		$startConfig->setDetach(true);
		
		$execmanager = $docker->getExecManager();
		$response = $execmanager->create('4e2697d63852',$execconfig);

		$responseid = $response->getId();
		

		$find = $execmanager->find($responseid);
		$start = $execmanager->start($responseid, $startConfig);

		debug($find);
		debug($start);


		
	} catch( \Exception $e) {
		debug($e);
	}
    return view('welcome');
});
```

After running `localhost` on my host system, i have checked the workspace container.
There is now a directory "hugo2" inside the "tmp" directory.

Hope this helps you to continue with whatever you try to do :)

Greets
Marcus

**Comment by xrobau** [comment]
I had to do the same thing, and ended up having to reverse engineer the tests to try to figure this out.

```
<?php

namespace Sangoma\TestSuite;

use Docker\API\Model\ExecConfig;
use Docker\API\Model\ExecStartConfig;
use Docker\Manager\ExecManager;

class Docker extends \Docker\Docker {

        /**
         * Execs a command in a running container, and returns the result. Note that
         * docker doesn't support returning the exit code.
         *
         * @param string $container     Container identifier
         * @param array $cmd            Array of commands to send to the container
         *
         * @returns array [ stdout, stderr ]
         */

        public function exec($container, $cmd) {

                if (!is_array($cmd)) {
                        throw new \Exception("cmd must be an array of strings");
                }

                $ec = new ExecConfig;
                $ec->setTty(true);
                $ec->setAttachStdout(true);
                $ec->setAttachStderr(true);
                $ec->setCmd($cmd);

                $sc = new ExecStartConfig;
                $sc->setDetach(false);

                $execid = $this->getExecManager()->create($container, $ec)->getId();
                $stream = $this->getExecManager()->start($execid, $sc, [], ExecManager::FETCH_STREAM);

                $stdoutText = "";
                $stderrText = "";

                $stream->onStdout(function ($stdout) use (&$stdoutText) {
                        $stdoutText .= $stdout;
                });
                $stream->onStderr(function ($stderr) use (&$stderrText) {
                        $stderrText .= $stderr;
                });
                $stream->wait();

                return [ "stdout" => $stdoutText, "stderr" => $stderrText ];
        }

}
```

I leave this here in the hope that someone is actually trying to improve the documentation and can provide this as an example..

**Comment by joelwurtz** [comment]
Closing this as this issue is rather old.

**Comment by Kolyunya** [comment]
@joelwurtz your first comment about exec manager seems to be outdated. Is there any high-level API to execute a command inside a container and get its output? The solution from https://github.com/docker-php/docker-php/issues/178#issuecomment-317205716 seems ridiculously complicated for a high-level library.

**Comment by dbjpanda** [comment]
Any one reached here may find this example useful as some changes has been done in latest version of API. 

```
<?php
use Docker\Docker;
use Docker\API\Model\ContainersIdExecPostBody;
use Docker\API\Model\ExecIdStartPostBody;

$docker = Docker::create();

$execConfig = new ContainersIdExecPostBody();
$execConfig->setTty(true);
$execConfig->setAttachStdout(true);
$execConfig->setAttachStderr(true);
$execConfig->setCmd(['mkdir', '/tmp/testDir']);

$execid = $docker->containerExec('android',$execConfig)->getId();
$execStartConfig = new ExecIdStartPostBody();
$execStartConfig->setDetach(false);
$output = $docker->execStart($execid,$execStartConfig);

var_dump($output);
```
