### ISSUE TITLE
PHP Fatal error:  Class 'Docker\Http\DockerClient' not found in /var/www/html/final/index.php on line 4

### ISSUE THREAD

**Issue by witsriram** [docker-php/docker-php#182]
I followed instruction.. 

composer require docker-php/docker-php

vi index.php
-------------------------------------------------------------------------------
#!/usr/bin/php
<?php
require_once 'vendor/autoload.php';
$client = new Docker\Http\DockerClient(array(), 'unix:///var/run/docker.sock');
$docker = new Docker\Docker($client);
$manager = $docker->getContainerManager();

# list
$containers = $manager->findAll();
foreach ($containers as $container) {
  $manager->inspect($container);
  print($container->getID() . " " . $container->getName() . "\n");
}

# stop a container called vanilal1
$container = $manager->find('vanilla1');
$manager->stop($container);
print_r($container->getRuntimeInformations()['State']);
-------------------------------------------------------------------------------

But i see below error,

PHP Fatal error:  Class 'Docker\Http\DockerClient' not found in /var/www/html/final/index.php on line 4

**Comment by joelwurtz** [comment]
I think you are refering to the old documentation / version of this project which is not supported anymore, where did you find the documentation ? (it should not be present)

The documentation for the new version is available here : http://docker-php.readthedocs.org/en/latest/
