### ISSUE TITLE
How to create a container

### ISSUE THREAD

**Issue by smalot** [docker-php/docker-php#184]
Hi,

The documentation is quite poor about how to create a container, and the single sample code is not working on my environment.
Does someone else perform to create a container with the current API ?
However, I'm correctly retrieving the list of current running container.

````php
<?php

include 'vendor/autoload.php';

use Docker\Docker;
use Docker\API\Model\ContainerConfig;

$docker = new Docker();
$containerManager = $docker->getContainerManager();

$containerConfig = new ContainerConfig();
$containerConfig->setImage('busybox:latest');
$containerConfig->setCmd(['echo', 'I am running a command']);

try {
  $containerCreateResult = $containerManager->create($containerConfig);
} catch (\Exception $e) {
  var_dump($e);
  throw $e;
}
````

This sample code generate this error:

````sh
Fatal error: Uncaught exception 'Http\Client\Plugin\Exception\ClientErrorException' with message 'Not Found' in /data/www/test/vendor/php-http/plugins/src/ErrorPlugin.php:45
Stack trace:
#0 /data/www/test/vendor/php-http/plugins/src/ErrorPlugin.php(27): Http\Client\Plugin\ErrorPlugin->transformResponseToException(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /data/www/test/vendor/php-http/promise/src/FulfilledPromise.php(35): Http\Client\Plugin\ErrorPlugin->Http\Client\Plugin\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /data/www/test/vendor/php-http/plugins/src/ErrorPlugin.php(28): Http\Promise\FulfilledPromise->then(Object(Closure))
#3 /data/www/test/vendor/php-http/plugins/src/PluginClient.php(133): Http\Client\Plugin\ErrorPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#4 /data/www/test/vendor/php-http/plugins/src/PluginClient.php(147): Http\Client\Plugin\PluginClient->Http\Client\Plugin\{closure}(Object(GuzzleHttp\Psr7\Request))
#5 /data/www/test/vend in /data/www/test/vendor/php-http/plugins/src/ErrorPlugin.php on line 45
````

What am I doing wrong ?
Many thanks

**Comment by smalot** [comment]
Actually, am I doing the good thing ?
Shouldn't use instead the 'run' command ?

Any help will be appreciate

**Comment by hxpro** [comment]
In your code you just create container. After you create one, you must start it. Try add this line after your create command.
```
$containerManager->start($containerCreateResult->getId());
```

**Comment by smalot** [comment]
Unfortunately the container is not created.
I encountered an issue : "Not Found".

**Comment by hxpro** [comment]
Try `docker events` (Get real time events from the server).

**Comment by smalot** [comment]
When I use the following command line, I can see events in 'docker events':

````sh
docker run -d busybox:latest echo 'I am running a command'
````

but nothing with the sample code using 'docker-php'.
I've got directly the exception.

Can you try the sample code on your side ?

**Comment by hxpro** [comment]
Which exception you got? Check permission to docker socket. Try to run it as root.

**Comment by smalot** [comment]
The error is:

````
'Http\Client\Plugin\Exception\ClientErrorException' with message 'Not Found'
````

I doubt this issue refers to a permission.
I have the same issue using 'root' account.

**Comment by smalot** [comment]
OMG !

I found my issue. That's because the image hasn't been already pulled.
So I need to pull it first, and then create the container.

I hope to obtain the same result as done using the command line `docker run ...` which automatically pull the image if missing ...

**Comment by hxpro** [comment]
heh ;)

**Comment by smalot** [comment]
Finally I performed to create an image, create a container and start it ! Youhou !!!!
However, I'm facing with a strange behavior when reading logs.
I've strange chars before the right log content:

````
> hexdump -C response.log
00000000  01 00 00 00 00 00 00 17  49 20 61 6d 20 72 75 6e  |........I am run|
00000010  6e 69 6e 67 20 61 20 63  6f 6d 6d 61 6e 64 0a 0a  |ning a command..|
00000020  73 74 72 69 6e 67 28 32  29 20 22 6f 6b 22 0a     |string(2) "ok".|
0000002f
````

Here is my sample code to read logs:
````php
$containerLogsResult = $docker->getContainerManager()->logs('23b0da3fff80', ["stderr"=>true, "stdout"=>true]);
echo $containerLogsResult->getBody()->getContents();
````

According to the documentation, it seems quite hard to read logs.
Any advice ?

**Comment by smalot** [comment]
Found solution, not very smart, but it works:

````php
// Send logs command.
$containerLogsResult = $docker->getContainerManager()->logs('23b0da3fff80', ['stderr' => TRUE, 'stdout' => TRUE]);
// Retrieve logs content.
$output = $containerLogsResult->getBody()->getContents();

// Stream id: (1 for standard output, 2 for error ?)
$hex = bin2hex($content[0]);
$streamId = hexdec($hex);

$hex = bin2hex(substr($content, 1, 7));
$length = hexdec($hex);

// Contains real logs.
$content = substr($content, 8, $length);
````

This code needs to be enhanced to support multiple streams in a single response.
Hope it helps someone.   :-)

**Comment by hxpro** [comment]
What about function called `trim`?

**Comment by smalot** [comment]
With long text, the length header which is in binary encoded can be greater than 64 which will generate a visible char.
The other drawback with a simple trim is when the response contains 2 streams (error and standard output).

**Comment by joelwurtz** [comment]
Forget that logs methods use the same format as the attach one, will try to override the method in the ContainerManager to have something more reusable.

In the meantime, you can maybe use the `DockerRawStream` which can read this : 

```
$stream = new DockerRawStream($response->getBody());
```

Then you should be able to get stderr / stdout in the same way as the `attach` method (by using `onStdout`, `onStderr` and `wait` method of this stream)

**Comment by smalot** [comment]
Excellent !
I'll try it.

**Comment by darkwinternight** [comment]
Am I doing something wrong? Because that exact code works fine for me:

```php
// Send logs command.
$containerLogsResult = $docker->getContainerManager()->logs('23b0da3fff80', ['stderr' => TRUE, 'stdout' => TRUE]);
// Retrieve logs content.
$output = $containerLogsResult->getBody()->getContents();
```

**Comment by joelwurtz** [comment]
It's good but you can have weird characters and you loose information about a line being from stderr or stdout.

In fact you read the raw content from the log which use the vnd raw docker stream format (cf https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#attach-to-a-container) 

(And most of the time the first byte indicator is translated to a non displayable character for ASCII)

**Comment by darkwinternight** [comment]
Could you give me an example on how to use the stream? Do I still use the `logs` method or do I use `attach`?

**Comment by smalot** [comment]
On my side I tried this, but without success:

````php
  $containerLogsResult = $docker->getContainerManager()->logs(
    '23b0da3fff80',
    ['stderr' => TRUE, 'stdout' => TRUE]
  );
  $stream = new \Docker\Stream\DockerRawStream($containerLogsResult->getBody());
  $stream->onStdout(function($stdout) {
    echo $stdout;
  });
  $stream->onStderr(function($stderr) {
    echo $stderr;
  });
````

nothing is printed  :-(

**Comment by smalot** [comment]
Found !
You need to call at the end the 'wait()' method:

````php
$containerLogsResult = $docker->getContainerManager()->logs(
    '23b0da3fff80',
    ['stderr' => TRUE, 'stdout' => TRUE]
  );
  $stream = new \Docker\Stream\DockerRawStream($containerLogsResult->getBody());
  $stream->onStdout(function($stdout) {
    echo $stdout;
  });
  $stream->onStderr(function($stderr) {
    echo $stderr;
  });
  $stream->wait();
````

But it's not easy to work with callback function in this context.
It should be better to access directly to standard output and standard stream content.

**Comment by darkwinternight** [comment]
That's what I was trying but it doesn't work. The reason is that the `readFrame()` method reads the first 8 bytes which -- at least in my case -- is not a header but rather the first 8 ASCII characters of the container output (in my case that is `Using CA` because the log starts with `Using CATALINA_BASE:   /opt/tomcat`).

As a consequence, `$decoded['type']` is neither `0`, `1` or `2` and no callback gets called.

Using Docker version 1.10.3, build 20f81dd.

**Comment by smalot** [comment]
I've just made a PR with a sample code which is working in my case.
@darkwinternight : can you test it on your side ?

Here is a sample code to use it:

````php
/** @var \Docker\Stream\DockerRawStaticStream $containerLogsResult */
$containerLogsResult = $docker->getContainerManager()->logs(
  $id,
  ['stderr' => TRUE, 'stdout' => TRUE]
);

echo 'standard output: ' . $containerLogsResult->getStdOut() . "\n";
echo 'standard error: ' . $containerLogsResult->getStdErr() . "\n";
````
