### ISSUE TITLE
RegistryNormalizer and SystemInformationNormalizer needs a check for null values.

### ISSUE THREAD

**Issue by darkwinternight** [docker-php/docker-php#186]
In `RegistryNormalizer:44`, the value of `$data->{'Mirrors'}` can be null, making the following code throw an error.

```php
foreach ($data->{'Mirrors'} as $value) {
     $values[] = $value;
}
```

Same goes for `SystemInformationNormalizer:86` where the value of `$data->{'SystemStatus'}` can be null

```php
foreach ($data->{'SystemStatus'} as $value_2) {
    $values_3 = [];
    foreach ($value_2 as $value_3) {
        $values_3[] = $value_3;
    }
    $values_2[] = $values_3;
}
```

A simple check solves the issue: 

```php
if (property_exists($data, 'SystemStatus') && ! is_null($data->{'SystemStatus'})) {
```

**Comment by darkwinternight** [comment]
So, I figured out that `docker-swagger.json` needs to be modified and the type needs to be changed to `"type": ["array", "null"],`.

Same goes for `Labels` and `Env` in `ContainerConfigNormalizer.php` by the way.

**Comment by joelwurtz** [comment]
Thanks to @Synpase791 it should be good now, version 1.22.2 and 1.21.3 has been tagged with the fix and other small changes

**Comment by joelwurtz** [comment]
I will close this, don't hesite to reopen it if you still have this issue

**Comment by darkwinternight** [comment]
Seen it! Thanks @joelwurtz and @Synapse791 !

**Comment by Synapse791** [comment]
No problem!

@joelwurtz Awesome package =]
