### ISSUE TITLE
Error with PortBinding Remote API v1.23

### ISSUE THREAD

**Issue by blurGroup** [docker-php/docker-php#196]
When trying to get a container by it's name, I'm getting the following exception:

```
ErrorException in PortBindingNormalizer.php line 42:
First parameter must either be an object or the name of an existing class

in PortBindingNormalizer.php line 42
at HandleExceptions->handleError('2', 'First parameter must either be an object or the name of an existing class', '/opt/terraformer/vendor/docker-php/docker-php/generated/Normalizer/PortBindingNormalizer.php', '42', array('data' => array(object(stdClass)), 'class' => 'Docker\API\Model\PortBinding', 'format' => 'raw', 'context' => array('rootSchema' => object(Container)), 'object' => object(PortBinding)))
at property_exists(array(object(stdClass)), 'HostPort') in PortBindingNormalizer.php line 42
...
```

which looks to me like the normalizer is expecting the PortBinding from the array.

Section of the JSON string passed to PortBindingNormalizer::deserialize():
```json
"Ports":{"8080/tcp":[{"HostIp":"0.0.0.0","HostPort":"80"}]}
```

Adding the following code at line 32 of `generated/Normalizer/PortBindingNormalizer.php` as a test fixes the problem and no other exception is thrown.

```php
        if (is_array($data))
            $data = $data[0];
```

Unfortunately my knowledge of swagger and jane-openapi is lacking and I'm not quite sure how to sort this issue in a proper way.

## Extra Info
Docker PHP Version: docker-php/docker-php (dev-master 969b7da)

```sh
~$ docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64
```

**Comment by Synapse791** [comment]
I think it's this part of the docker-swagger that needs updating:

```json
 230         "PortBindings": {
 231           "type": "object",
 232           "additionalProperties": {
 233             "$ref": "#/definitions/PortBinding"
 234           }
 235         },
```

**Comment by atroy** [comment]
Hi that should be updated in dev version, or better say 4ea4afd03008f41894582e69fe470d060e616bdf

**Comment by Synapse791** [comment]
I see that commit on the branch 1.22 but I can't figure out how to get that version with composer.

I've tried

**Comment by atroy** [comment]
Try "docker-php/docker-php": "dev-master#4ea4afd03008f41894582e69fe470d060e616bdf" and set stability flag to dev.

**Comment by Synapse791** [comment]
That's worked a treat! Thanks!

**Comment by atroy** [comment]
No problem ;-) Can you please close the issue?

**Comment by joelwurtz** [comment]
Just tag 1.22.3 with last commits, so you can go back to stable version if you prefer
