### ISSUE TITLE
How to do the very simple command "docker run --rm -v /toto:/toto ubuntu ls /toto" ?

### ISSUE THREAD

**Issue by ebuildy** [docker-php/docker-php#199]
Hello,

I would like to achieve a very basic thing, run a container with a volume and get back the stdout response.

What would be the best approach? (I start to play with docker-php but I end up with more than 20 lines of code :-(), thanks you.

**Comment by joelwurtz** [comment]
Like i said in a previous issue volume attachment seems not possible, it's a missing thing :/

For running a container did you look at http://docker-php.readthedocs.io/en/latest/cookbook/container-run/ ?

**Comment by drsect0r** [comment]
@joelwurtz I think that host volumes are working. You set this in the `HostConfig` object. 

``` PHP

use Docker\Docker;                   
use Docker\API\Model\ContainerConfig;
use Docker\API\Model\HostConfig;

$docker = new Docker();
$containerManager = $docker->getContainerManager();

$hostConfig = new HostConfig();
$hostConfig->setBinds(['/toto:/toto']);

$containerConfig = new ContainerConfig();
$containerConfig->setHostConfig(setHostConfig);
$containerConfig->setImage('busybox:latest');
$containerConfig->setCmd(['echo', 'I am running a command']);

$containerCreateResult = $containerManager->create($containerConfig);

$containerManager->start($containerCreateResult->getId());
```

**Comment by crazyscience** [comment]
This does seem to work, but it needs to be in the documentation. Without documentation, it may as well not exist.

**Comment by joelwurtz** [comment]
Closing this as this issue is rather old.

Yes need this in the documentation, but overall docs on the endpoint and model is now very complete, so it may be enough.
