### ISSUE TITLE
Statistics of a container

### ISSUE THREAD

**Issue by dewolftimothy** [docker-php/docker-php#201]
Is there a possibility to see the memory usage and CPU usage of a container live with the library?

**Comment by aiphee** [comment]
I know this ain't a forum, but could someone please answer and close this?

**Comment by CliffLin** [comment]
``` $docker->getContainerManager()->stats(container id) ```

**Comment by aiphee** [comment]
Well i tried that much, but i have failed to get contents.
I did this:
```PHP
$docker->getContainerManager()->stats($id)->getBody()->getContents();
```
But i get timeout, i guess it might be caused by getting too much data, but i have no idea how to get concrete data.

**Comment by joelwurtz** [comment]
Hey,

Sorry for the no answer been busy for a while, it should be possible to see in real time what is happening on a docker, however it require some works on this lib as there it must be encapsulated with some apis.

Getting content will certainly timeout, as the connection never finish (as it's a live stream), so PHP will certainly end it by himself.

If you want to look more into it and do a PR, you can check how others stream are already handled in https://github.com/docker-php/docker-php/blob/1.24/src/Manager/ImageManager.php#L38 or https://github.com/docker-php/docker-php/blob/1.24/src/Manager/ContainerManager.php#L25

(depends mainly on which stream is returned).

**Comment by joelwurtz** [comment]
Closing this as this issue is rather old.
