### ISSUE TITLE
Archive (methods) features

### ISSUE THREAD

**Issue by Alexwijn** [docker-php/docker-php#204]
Hi,

Any chance the archive methods (`getArchive`, `getArchiveInformation`, `putArchive`) on the `ContainerManager` will receive some extra code to parse the reponse from the Docker API?

According to the Docker API documentation it returns a `TAR STREAM` but I'm just testing to read a simple text file in a container. When I read out the contents it prepends a file header (I think) with filename along with the contents of the file. So not sure how to parse it correctly.

Maybe someone can show me a way to run things like `cat text.txt` and save that in a variable, that would be fine to.

Thanks!

**Comment by joelwurtz** [comment]
Done in 2.0
