### ISSUE TITLE
Missing --net-alias functionality.

### ISSUE THREAD

**Issue by psmitty7373** [docker-php/docker-php#205]
It'd be nice to be able to use the "--net-alias" functionality for user-defined networks.  It appears there is a new addition to the container create json:

<beginning omitted...>
      "NetworkingConfig": {
      "EndpointsConfig": {
          "isolated_nw" : {
              "IPAMConfig": {
                  "IPv4Address":"172.20.30.33",
                  "IPv6Address":"2001:db8:abcd::3033"
              },
              "Links":["container_1", "container_2"],
              "Aliases":["server_x", "server_y"]
          }
      }

Where aliases are DNS aliases.

See https://docs.docker.com/engine/userguide/networking/configure-dns/ for more info.

**Comment by joelwurtz** [comment]
It should be available in 2.0
