### ISSUE TITLE
setNames method doesnt work

### ISSUE THREAD

**Issue by highcmd** [docker-php/docker-php#207]
I encountered problem while creating a container, setNames doesnt sets container name and its generated randomly by docker

my code:
`$containerConfig = new ContainerConfig();
$containerConfig->setNames(['my-awesome-container']);
$containerConfig->setHostConfig($hostConfig);
$containerConfig->setImage('test/demo:latest');`

**Comment by psmitty7373** [comment]
I ran into the same issue... setNames not working... the code below will work.

    $containerCreateResult = $containerManager->create($containerConfig, ['name' => 'bar']);

**Comment by joelwurtz** [comment]
The documentation was bad and setNames in fact should not be used (as it's a read only field), see the updated documentation too see how it works (you should set the name in the create command like @psmitty7373 said)
