### ISSUE TITLE
How to set static IP address for docker container

### ISSUE THREAD

**Issue by zenerdeor** [docker-php/docker-php#211]
Hi,
I am having a problem about setting static ip for a docker container.
In docker I've created a network with the following command.
`docker network create --subnet=172.18.0.0/16 mynet`

Normally I set the ip with this command.
`docker run --net mynet --ip 172.18.0.9 -it ubuntu:14.04 bash`

In docker-php I try this.

```
use Docker\API\Model\ContainerConfig;
use Docker\API\Model\HostConfig;
use Docker\API\Model\NetworkConfig;
use Docker\API\Model\ContainerNetwork;

$client = new Docker\DockerClient([
        'remote_socket' => 'tcp://172.17.0.1:4243',
        'ssl' => false,
]);

$docker = new Docker\Docker($client);

$hostConfig = new HostConfig();
$hostConfig->setNetworkMode('mynet');

$containerNetwork = new ContainerNetwork();
$containerNetwork->setIPAddress('172.18.0.9');

$networkConfig = new NetworkConfig();
$networkConfig->setNetworks(new \ArrayObject([
           'mynet' => $containerNetwork
]));

$containerConfig = new ContainerConfig();
$containerConfig->setImage('ubuntu:14.04');
$containerConfig->setHostConfig($hostConfig);
$containerConfig->setNetworkSettings($networkConfig);
$containerConfig->setOpenStdin(true);

$containerManager = $docker->getContainerManager();

$containerCreateResult = $containerManager->create($containerConfig);

$containerManager->start($containerCreateResult->getId());
```

But it doesn't work.
IP Address of docker is 172.18.0.2
Can you tell me what should I do or what I did wrong.

**Comment by joelwurtz** [comment]
I don't know :/, best way to know how to do it, will be to read docker api documentation : https://docs.docker.com/engine/api/v1.36/ and also the doc of the endpoint / model.

If you find a way, it would be nice to do a PR with a cookbook in the documentation explaining how to do it.

Closing this ATM as this issue is rather old.
