### ISSUE TITLE
Need to be root to access unix socket ?

### ISSUE THREAD

**Issue by revollat** [docker-php/docker-php#215]
Hi,

I have a php app running in a container as www-data user (with nignx et php-fpm)
The /var/run/docker.sock is mout inside the container.
With this config I can't access the socket (permission denied). 

So what is the best practice here ? running all as root ? (but I don't think it's a good idea). Change permission or group to allow www-data to access the socket ? Or maybe running a "wrapper" as root that the www-data user can call ?

How do you do that ?

Thanks :)

**Comment by revollat** [comment]
For now I ran 
socat TCP-LISTEN:2380,bind=172.17.0.1,fork UNIX-CONNECT:/var/run/docker.sock
inside host so I can access the socket from the API : 

        $client = new DockerClient([
            'remote_socket' => 'tcp://172.17.0.1:2380',
            'ssl' => false,
        ]);
        $docker = new Docker($client);

it works but I don't think it's the right way ....

**Comment by joelwurtz** [comment]
You can normally use the group docker (add www-data to the docker group), but you have to map the correct gid from your host to the container, and also make sure that the socket is writable and readable on the group `.5.` (this is by default if my memory is good).

**Comment by revollat** [comment]
Hi, 
it's bassically what I've done 

Inside the host i'm www-data, member of the docker group :

`
$ id
uid=33(www-data) gid=33(www-data) groups=33(www-data),999(docker)
`

Inside the container I'm www-data (same id=33) should I add the docker group (with id 999) inside the container too ? 

`
$ docker-compose exec app bash -c 'su - www-data'
www-data@e9642e093f64:~$ id
uid=33(www-data) gid=33(www-data) groups=33(www-data)
www-data@e9642e093f64:~$ socat - UNIX-CONNECT:/var/run/docker.sock
2016/08/02 15:03:58 socat[124] E connect(5, AF=1 "/var/run/docker.sock", 22): Permission denied
`

**Comment by joelwurtz** [comment]
> Inside the container I'm www-data (same id=33) should I add the docker group (with id 999) inside the container too ?

Yes, i think this should work

**Comment by revollat** [comment]
Yes I've added this to my dockerfile and it works ;)

```
RUN groupadd -r -g 999 docker
RUN usermod -aG docker www-data
```
