### ISSUE TITLE
API v1.24 : swarm mode

### ISSUE THREAD

**Issue by revollat** [docker-php/docker-php#216]
Hello,

I currently developping an app written in PHP to leverage the power of the new docker swarm mode (v1.12 of docker, v1.24 of the API). 

I can't see anything related to the swarm mode (https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/3-7-swarm) in the docker-php lib 

I'm really interested in contributed to docker-php on swarm mode.

What do you think ? is there any contributor who already working on this ?

Thanks !

**Comment by joelwurtz** [comment]
Currently this lib does not support 1.24 of API (or 1.12)

> What do you think ? is there any contributor who already working on this ?

I have begginning to work on 1.12 and a better integration of container config, but did not push anything.

If you don't mind to wait, i'm planning to add this support next week as i have manage to get some days in my office to fully work on open source.

However if you want to do it, make sure to edit the swagger schema with the changes from 1.24 and regenerate the code with this new schema (do not change directly the generated code)

**Comment by revollat** [comment]
I'll wait for your push. Then I could test/improve the code by using it in my project.

Thanks :)

**Comment by joelwurtz** [comment]
It's live on the 1.24 branch (use 1.24@dev in composer), do you have time to test this ? Would love to have feedback before tagging.

**Comment by revollat** [comment]
Thanks. Sure I'll test it during the next week and give you feedback.
