### ISSUE TITLE
How to set Network (use a previously created network)

### ISSUE THREAD

**Issue by frjaraur** [docker-php/docker-php#217]
I am trying to start a container using a previously created network, but I can't.... (I followed previous issues [#211](https://github.com/docker-php/docker-php/issues/211) and [#175](https://github.com/docker-php/docker-php/issues/175) ).

$nwc = new NetworkConfig();
$nwc->setNetworks(new \ArrayObject([
           $container_network_mode => $containerNetwork
]));
//$containerManager = $this->docker->getContainerManager();
$containerConfig = new ContainerConfig();
$containerConfig
    ->setImage('busybox:latest')
    ->setEnv(['foo=barr'])
    ->setNetworkSettings($nwc)
    ->setCmd(['echo', 'I am running a command']);

Call to undefined method Docker\API\Model\ContainerConfig::setNetworkSettings()
ContainerConfig has NetworkingConfig object, but don't know how to set networking now?¿

I have tryied to create container using config and then change container network settings before start it, but It doesn't work either...

$hostConfig = new HostConfig();
$hostConfig->setNetworkMode($source_container_network_mode);

$cloned_container->setHostConfig($hostConfig);

If I preview new container configs before start it, I can see my changes in network but when it starts it get default ones...
Many Thanks

**Comment by Tyldar** [comment]
Hey ! Did you figured out the solution for your problem ? I've the same now, can't find how to apply a NetworkConfig object to a container...

**Comment by summergeorge** [comment]
I find it. 
` $portblinding = new PortBinding();
        $portblinding->setHostPort('6033');
        $portblinding->setHostIp('0.0.0.0');

        $ports = [];
        $ports[] = $portblinding;

        $hostconfig = new HostConfig();
        $hostconfig->setPortBindings(new \ArrayObject(['80/tcp'=>$ports]));
        $containerConfig->setHostConfig($hostconfig);`

**Comment by matejvelikonja** [comment]
since @summergeorge solution did not work for us, we actually needed to put it in the same network and not just use port binding, we used the following solution to attach new container to existing network

```php
$hostConfig = new HostConfig();
$hostConfig->setNetworkMode('existing_network_name');

$containerConfig = new ContainerConfig();
$containerConfig->setHostConfig($hostConfig);
```

**Comment by joelwurtz** [comment]
Closing this, will accept a PR on documentation if someone want to write a cookbook for it.
