### ISSUE TITLE
[1.24] DateTime parsing not correct

### ISSUE THREAD

**Issue by marcvdm** [docker-php/docker-php#218]
The date time parsing for Datetimes that are in RFC3339Nano `2006-01-02T15:04:05.999999999Z07:00` can not be parsed by certain normalizers.

Either they need a trick to works or filter out the nanoseconds part.
PHP cannot handle the RFC3339Nano that GO uses as default.

**Comment by jenspapenhagen** [comment]
the error is well known in PHP
[PHP bug 64814](https://bugs.php.net/bug.php?id=64814)
, but with custom code it can be fix very easily

`
date_default_timezone_set('UTC');
$fixit = (explode(".","2006-12-12T10:00:00.999999999-04:00"));
var_dump(date_parse( $fixit[0] ));
`

**Comment by marcvdm** [comment]
I found a similar solution but the code that parses the dates is generated. So i don't know where to put this.

**Comment by jenspapenhagen** [comment]
okay that is a problem.

**Comment by marcvdm** [comment]
It would be awesome if the generator jane/jane would let us define a custom method as a format to parse the datetime.

I could not find any way of hooking into it and adding our own normalizer method.

**Comment by joelwurtz** [comment]
Fixed in 2.0
