### ISSUE TITLE
Errors in cookbook and using SetNames and ContainerInfo object in new version

### ISSUE THREAD

**Issue by stemax** [docker-php/docker-php#220]
Examples with **errors** here http://docker-php.readthedocs.io/en/latest/cookbook/container-run/ and https://github.com/docker-php/docker-php/blob/1.24/docs/cookbook/container-run.md :
`$containerConfig->setNames(['my-container-unique-name']]);`
 Plus, In latest version we can't use $containerConfig->**setNames**
https://github.com/docker-php/docker-php/commit/039517f587ce87289351163a73995ad2bfd9a34c
As I understood now we need use **ContainerInfo** instead **ContainerConfig**, but then we can't use method **setTty**... 
Could you explain **how to use latest version** of docker-php?

For example. My code (working on old version):

```
            $containerConfig = new ContainerConfig();
            $containerConfig->setImage('image_path');
            $containerConfig->setNames([$name]);
            $containerConfig->setTty(true);

            try {
                $docker->getContainerManager()->create($containerConfig, ['name' => $name]);
            } catch (\ErrorException $e) {
                return [
                    'code' => $e->getCode(),
                    'error' => $e->getMessage()
                ];
            }
```

Thanks.

**Comment by joelwurtz** [comment]
Documentation should be correct in 2.0
