### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by ijry** [docker-php/docker-php#222]
Why Permission denied

$docker = new Docker();
$containers = $docker->getContainerManager()->findAll();

**Comment by ijry** [comment]
done  is's perssion issue

**Comment by noxify** [comment]
How did you solved it?

I had/have the same problem even when I rebuild my environment.
Currently my workaround is to set the CHMOD to 777 for the `/var/run/docker.sock` in my nginx container.

**Comment by ijry** [comment]
it's the user&group caused this bug,you should add nginx's user  such as www-data into docker,then reboot!

**Comment by noxify** [comment]
yeah - now it works - thanks :)
