### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by ijry** [docker-php/docker-php#223]
Why  Not Found  404?
`$docker = new Docker();
            $containerManager = $docker->getContainerManager();
            $containerConfig = new ContainerConfig();
            $containerConfig->setImage('busybox:latest');
            $containerConfig->setCmd(['echo', 'I am running a command']);
            $containerConfig->setAttachStdin(true);
            $containerConfig->setAttachStdout(true);
            $containerConfig->setAttachStderr(true);
            $containerCreateResult = $containerManager->create($containerConfig);`

**Comment by ijry** [comment]
@ubermuda @LeeSaferite @deweller @nubs @jeffturcotte

**Comment by ijry** [comment]
@ubermuda help

**Comment by ministicraft** [comment]
you need to pull your image first
