### ISSUE TITLE
Wrong definition of ProgressDetail

### ISSUE THREAD

**Issue by dontub** [docker-php/docker-php#225]
The type ProgressDetail has the properties `code` and `message`, but it should have the properties `current` and `total`.
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/create-an-image

**Comment by joelwurtz** [comment]
This is now the case in 2.0 see https://github.com/docker-php/docker-php-api/blob/4.1.36/src/Model/ProgressDetail.php
