### ISSUE TITLE
Missing labels for build image

### ISSUE THREAD

**Issue by lislon** [docker-php/docker-php#230]
From [docs api 1.24](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/build-image-from-a-dockerfile) I see there is `labels` parameter, but I can't use it in docker-php:

```php
// ... tests/Manager/ImageManagerTest.php
$contextBuilder = new ContextBuilder();
$contextBuilder->from('ubuntu:precise');
$contextBuilder->add('/test', 'test file content');

$context = $contextBuilder->getContext();
$buildStream = $this->getManager()->build($context->read(), [
    't' => 'test-image',
    'labels' => ['test-label' => 'yes']
], ImageManager::FETCH_STREAM);

````

Gives an error:

```
The option "labels" does not exist. Defined options are: "Content-type", "X-Registry-Config", "buildargs", "cpuperiod", "cpuquota", "cpusetcpus", "cpushares", "dockerfile", "forcerm", "memory", "memswap", "nocache", "pull", "q", "remote", "rm", "t".
```

Is there a way to set labels when building image?

**Comment by allentje** [comment]
I think they just need to update the parameters in the build method.
If you need this to work then just add:
`$queryParam->setDefault('labels', null);`

/generated/Resource/ImageResource.php:76

Worked for me :)

**Comment by joelwurtz** [comment]
This is now supported in 2.0
