### ISSUE TITLE
Errors in Jane

### ISSUE THREAD

**Issue by yippeykeiyay** [docker-php/docker-php#238]
When attempting to do anything, I am receiving errors triggered in Jane.

Simply instantiating a new Docker object like this...
```
$objDocker = new \Docker\Docker();
```

...produces this error...
`RawEncoder is deprecated since 1.4 and will be removed in 2.0, please use Joli\Jane\Runtime\Encoder\RawEncoder instead.`

I've also received the following error when trying to interact with a container:
`QueryParam is deprecated since 1.3 and will be removed in 2.0, please use Joli\Jane\OpenApi\Runtime\Client\QueryParam instead.`

Is anyone else experiencing these issues? 
I'm using `docker-php v1.24.0` with `PHP v5.6.27`

**Comment by joelwurtz** [comment]
Should be good on 2.0
