### ISSUE TITLE
Get IP Address of container

### ISSUE THREAD

**Issue by samsamm777** [docker-php/docker-php#240]
How can i get the IP address of the container ive just started?

```       
$containerCreateResult = $containerManager->create($containerConfig);
$id = $containerCreateResult->getId();
$containerManager->start($id);
```

**Comment by rousku** [comment]
$container = $containerManager->find($containerCreateResult->getId());
$containerIP = $container->getNetworkSettings()->getIPAddress();

**Comment by joelwurtz** [comment]
Thanks @rousku
