### ISSUE TITLE
Update to 1.27

### ISSUE THREAD

**Issue by withinboredom** [docker-php/docker-php#241]
I tried this myself but get errors generating the library. They now offer a swagger file for download: https://docs.docker.com/engine/api/v1.27/

**Comment by boonkerz** [comment]
yea but it does not generate :( any other?

**Comment by joelwurtz** [comment]
Don't think it will generate, however since i manage also jane openapi, will try to take a look at this swagger file to make it generate through jane openapi.

**Comment by boonkerz** [comment]
i think is many work to let it generate :)
because currently the swagger tools itself do not generate php client code from the docker swagger yaml file :(

**Comment by joelwurtz** [comment]
See https://github.com/docker-php/docker-php/pull/261

**Comment by joelwurtz** [comment]
2.0 is out and support API 1.25 to 1.36 and 1.27 is included :)
