### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by mraspe** [docker-php/docker-php#243]
Hello,

is it possible to use "docker-compose up" (docker-compose.yml) with docker-php?

Greetings
Mario

**Comment by TwanoO67** [comment]
We are looking for the same thing... Any update ?

**Comment by boonkerz** [comment]
Not now because docker-compose is only an client program.
https://github.com/docker/compose/issues/1033

**Comment by joelwurtz** [comment]
Docker compose is not at all related to this, as like said by @boonkerz it's a client program that uses the Docker API to manager containers.

This library will never intend to control docker compose (too much work / pain in the long term).
