### ISSUE TITLE
how to stdin in attach mode

### ISSUE THREAD

**Issue by mdtomy** [docker-php/docker-php#247]
hi, I have a question
I use $webSocketStream->write('list');

and then i use command to attach my docker console,
it really shows "list"
but.....
without Enter key to exec my command

can someone help me? 
Thanks

**Comment by joelwurtz** [comment]
Look here https://github.com/docker-php/docker-php/blob/1.24/tests/Manager/ContainerManagerTest.php#L88

You need to send a "\n" to simulate the enter key
