### ISSUE TITLE
Deprecated warnings

### ISSUE THREAD

**Issue by beloglazov91** [docker-php/docker-php#248]
Please fix this problem:

> Remaining deprecation notices (5)
> 
> ReferenceNormalizer is deprecated since 1.4 and will be removed in 2.0, please use Joli\Jane\Runtime\Normalizer\ReferenceNormalizer instead: 1x
>     1x in AppProjectCreateCommandTest::testCommandExecute from AGServerBundle\Tests
> 
> NormalizerArray is deprecated since 1.4 and will be removed in 2.0, please use Joli\Jane\Runtime\Normalizer\ArrayDenormalizer instead: 1x
>     1x in AppProjectCreateCommandTest::testCommandExecute from AGServerBundle\Tests
> 
> RawEncoder is deprecated since 1.4 and will be removed in 2.0, please use Joli\Jane\Runtime\Encoder\RawEncoder instead: 1x
>     1x in AppProjectCreateCommandTest::testCommandExecute from AGServerBundle\Tests
> 
> Resource is deprecated since 1.3 and will be removed in 2.0, please use Joli\Jane\OpenApi\Runtime\Client\Resource instead: 1x
>     1x in AppProjectCreateCommandTest::testCommandExecute from AGServerBundle\Tests
> 
> QueryParam is deprecated since 1.3 and will be removed in 2.0, please use Joli\Jane\OpenApi\Runtime\Client\QueryParam instead: 1x
>     1x in AppProjectCreateCommandTest::testCommandExecute from AGServerBundle\Tests

It reproduced at least on version 1.24.

**Comment by joelwurtz** [comment]
2.0 has been released and there is no more deprecation warning as it use lastest versions of jane
