### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by thib3113** [docker-php/docker-php#249]
Hello,
I use php 7.0.18 on ubuntu vm
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans

My code : 
```php
    use Docker\API\Model\ContainerConfig;
    use Docker\API\Model\HostConfig;
    use Docker\API\Model\RestartPolicy;
    use Docker\Docker;
    $docker = new Docker();
    $containerManager = $docker->getContainerManager();

    $docker_image = "portainer";

    try{
        $docker_image = $containerManager->find($docker_image);
        $containerManager->start($docker_image);
    }
    catch( Exception $e ){
        if($e->getCode() == 404){
            //container don't exist, create it
            //pull the image first
            $imageManager = $docker->getImageManager();
            $imageManager->create(null,array("fromImage" => "portainer/portainer:latest"));

            //start generation of the container
            $containerConfig = new ContainerConfig();
            $containerConfig->setImage('portainer/portainer:latest');

            $hostConfig = new HostConfig();
            $hostConfig->setBinds(['/var/run/docker.sock:/var/run/docker.sock','portainer:/data']);
        
            //set restart policy
            $restartPolicy = new restartPolicy();
            $restartPolicy->setName("always");
            $hostConfig->setRestartPolicy($restartPolicy);
        
            //set port binding
            $hostConfig->setPortBindings(array("9000/tcp"=> array("HostPort" => "9001")));
        
            $containerConfig->setHostConfig($hostConfig);
            $containerManager->create($containerConfig, array("name" => "portainer-test"));
        
        }
    }
```

What did I try to do : 
`docker pull portainer/portainer && docker run -d --name="portainer-test" -v "/var/run/docker.sock:/var/run/docker.sock" -v portainer:/data --restart always -p 9001:9000 portainer/portainer`

The error : 

> PHP Fatal error:  Uncaught Http\\Client\\Common\\Exception\\ServerErrorException: Internal Server Error in /var/www/html/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php:50
Stack trace:
-0 /var/www/html/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php(28): Http\\Client\\Common\\Plugin\\ErrorPlugin->transformResponseToException(Object(GuzzleHttp\\Psr7\\Request), Object(GuzzleHttp\\Psr7\\Response))
-1 /var/www/html/vendor/php-http/httplug/src/Promise/HttpFulfilledPromise.php(34): Http\\Client\\Common\\Plugin\\ErrorPlugin->Http\\Client\\Common\\Plugin\\{closure}(Object(GuzzleHttp\\Psr7\\Response))
-2 /var/www/html/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php(29): Http\\Client\\Promise\\HttpFulfilledPromise->then(Object(Closure))
-3 /var/www/html/vendor/php-http/client-common/src/PluginClient.php(160): Http\\Client\\Common\\Plugin\\ErrorPlugin->handleRequest(Object(GuzzleHttp\\Psr7\\Request), Object(Closure), Object(Closure))
-4 /var/www/html/vendor/php-http/client-common/src/PluginClient.php(174): Http\\Client\\Common\\PluginClient->Ht in /var/www/html/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php on line 50

I don't understand what is the problem, and I can't find where is the docker remote api log, to solve the problem .

**Comment by robertol** [comment]
What your docker version?

**Comment by thib3113** [comment]
17.06.0-ce

**Comment by robertol** [comment]
I think your problem is this version. This latest docker-php was launched to docker 1.12.

**Comment by thib3113** [comment]
Yes, I know ... but docker-php always use the api 1.24 ?

**Comment by josergc** [comment]
@thib3113 I have also the same problem that you. I am using `journalctl` to debug the problem. The socket of docker is a unix socket. In my case I request it like this

```
url = /containers/create?name=test-at-%2860829%7D
headers = {"Host":"localhost","Content-Type":"application\/json"}
body = {"Env":null,"Image":"mariadb","Labels":null,"Volumes":null,"ExposedPorts":null,"HostConfig":{"Binds":null,"Links":null,"LxcConf":null,"BlkioWeightDevice":null,"BlkioDeviceReadBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceWriteIOps":null,"PortBindings":{"3306\/tcp":{"HostPort":"60829"}},"Sysctls":null,"StorageOpt":null,"Dns":null,"DnsOptions":null,"DnsSearch":null,"ExtraHosts":null,"VolumesFrom":null,"CapAdd":null,"CapDrop":null,"GroupAdd":null,"Devices":null,"Ulimits":null,"SecurityOpt":null}}
```

then I get this error when I do `sudo journalctl -xeu docker`

```
level=error msg="Handler for POST /containers/create returned error: json: cannot unmarshal object into Go value of type []nat.PortBinding"
```

I hope this can help

**Comment by josergc** [comment]
this code allowed me to create a new container
```

        $containerManager = $docker->getContainerManager();
        $containerConfig = new ContainerConfig();
        $containerConfig->setImage('mariadb');
        $containerConfig->setExposedPorts(["3306/tcp" => ["k" => "v"]]);
        //$hostConfig = new HostConfig();
        //$hostConfig->setPortBindings(["3306/tcp"=> ["HostPort" => "{$this->mysql_random_port}"]]);
        //$containerConfig->setHostConfig($hostConfig);
        $containerCreateResult = $containerManager->create(
            $containerConfig,
            ['name' => $this->mysql_random_name]
            );
        $containerManager->start($containerCreateResult->getId());

```

**Comment by josergc** [comment]
I think I know what happened: in the page https://docs.docker.com/engine/api/v1.24/#31-containers appears an example, and the `PortBindings` must be like `"PortBindings": { "22/tcp": [{ "HostPort": "11022" }] },`, so I am missing one more array:
```
        $docker = new Docker();
        $containerManager = $docker->getContainerManager();
        $containerConfig = new ContainerConfig();
        $containerConfig->setEnv([
            "MYSQL_ROOT_PASSWORD=abc123test"
        ]);
        $containerConfig->setImage('mariadb');

        // This encodes {"3306/tcp":{...}} instead of {"3306/tcp":[]}. 
        // The web API expects {"3306/tcp":{}}
        $containerConfig->setExposedPorts(["3306/tcp" => ["k" => "v"]]);
        $hostConfig = new HostConfig();

        // one port requires a list of host ports objects
        $hostConfig->setPortBindings(["3306/tcp"=> [["HostPort" => "{$this->mysql_random_port}"]]]); 
        $containerConfig->setHostConfig($hostConfig);
        $containerCreateResult = $containerManager->create(
            $containerConfig,
            ['name' => $this->mysql_random_name]
            );
        $containerManager->start($containerCreateResult->getId());
```
that code worked for me

**Comment by thib3113** [comment]
It's worked for me too, thanks you
