### ISSUE TITLE
Add Type property to Mounts

### ISSUE THREAD

**Issue by WillGibson** [docker-php/docker-php#251]
It would be useful if \Docker\API\Normalizer\MountNormalizer and \Docker\API\Model\Mount dealt with the mount's Type property.

I have a feeling that this may be a case of adding it to docker-swagger.json? I'm not familiar with Jane Open Api, but would be happy to submit a PR to address this if that's where I need to start?

**Comment by Soullivaneuh** [comment]
Hi @WillGibson,

Is it related to my issue? #256

Thanks.

**Comment by WillGibson** [comment]
I think yours is different @Soullivaneuh, looks like you figured a solution out anyway :-)

**Comment by joelwurtz** [comment]
Yes basically @WillGibson you need to add the property to the schema file and then generate the code by using the bash file at the root of this repository

**Comment by WillGibson** [comment]
Bit of a time lag responding, but I've just submitted that PR @joelwurtz, and tested it where we use docker-php.

**Comment by joelwurtz** [comment]
This property is now available in 2.0
