### ISSUE TITLE
Update Jane, Docker API and PHP version

### ISSUE THREAD

**Issue by mburtscher** [docker-php/docker-php#252]
People need a newer version than 1.24 especially because this one is buggy with recent Docker versions like 1.30 / 1.31 (invalid type conversion etc.).

So I tried updating everything starting from the minimum PHP version, Jane Open-API generation tool and the Docker Swagger Spec (new YAML spec instead of JSON). I've managed to get everything working in my fork over here:

https://github.com/mburtscher/docker-php/tree/1.31

We are now using this fork in our internal project but it would be great to see these improvements in the regular `docker-php/docker-php` package. I think it makes no sense to maintain a second project.

What are your plans and is there kind of a roadmap / to-do to proceed on these issues?

**Comment by joelwurtz** [comment]
> So I tried updating everything starting from the minimum PHP version, Jane Open-API generation tool and the Docker Swagger Spec (new YAML spec instead of JSON).

Yes, i made at lot of changes to be sure that the swagger schema from docker is compatible with jane, instead of relying on the custom schema.

> We are now using this fork in our internal project but it would be great to see these improvements in the regular docker-php/docker-php package. I think it makes no sense to maintain a second project.

> What are your plans and is there kind of a roadmap / to-do to proceed on these issues?

I wanted to raise an issue + a tweet for passing this repository to other contributors, as i do not use anymore the docker api (still using docker, but not the API) and have too little time to maintain this in a correct way.

However, i and many collegues of mine are using Jane intensively and in many projects so it will be maintained on the long term.

I would gladly add you as a contributor on this repository so you can merge you recent changes and continue to maintain this if you want ?

**Comment by mburtscher** [comment]
Thank you for replying so quickly! I'm glad to hear that you are open for contributions and progress on the project.

I'd be happy to contribute some things that I'm able to. But I don't want to make promises I can't deliver. I don't know yet if I'll be able to seriously contribute over time and generate some momentum here.

For the beginning I could try to get the project on to recent versions and the latest Docker API scheme as described in the previous message in this issue. I could do the changes in a branch so you can review and comment on the changes.

What do you think about updating dependencies/libraries? How would you handle it in terms of semantic versioning? It's hard since the major/minor version of Docker API is used. Also using a new generator version will heavily influence the classes created. For example, my fork is definitely not backward compatible with the original version.

**Comment by joelwurtz** [comment]
> For the beginning I could try to get the project on to recent versions and the latest Docker API scheme as described in the previous message in this issue. I could do the changes in a branch so you can review and comment on the changes.

Fine, enough, not sure i will have time to review thoses changes, so i will certainly give you some write rights if i am too long.

> What do you think about updating dependencies/libraries? How would you handle it in terms of semantic versioning? It's hard since the major/minor version of Docker API is used. Also using a new generator version will heavily influence the classes created. For example, my fork is definitely not backward compatible with the original version.

My vision for the future was to drop the generated class here, do a documentation on how to use jane with the swagger schema of docker and then provide some useful class to decode special streams from docker (vfs / multi json / ... )

So this library would be resumed to a few helper classes and a documentation, then people would use their own version of docker api and just use jane to have the generated classes.

WDYT ?

**Comment by mburtscher** [comment]
OK, that's a very different approach to the current project. I have a few concerns:

- When I first found this library I was looking for a "PHP SDK for the Docker API". So I was expecting a "working client library" rather than a toolkit to build it myself.
- Even the latest YAML files from Docker cannot be parsed as expected. So every user would run into problems with that.
- Also there are some specifications missing leading to invalid code that needs to be fixed manually. That shouldn't be the normal case, but it is now.
- As a developer I'd have to maintain the client library in my own code repository although it's generated. Doesn't feel nice. Same is true for this project but it's only a single point not every consuming project.

Having generated shipped as a SDK feels strange, but together with the additional classes, tests and fixes it makes sense.

Maybe we could just drop semver (I know, doesn't feel right) and suggest that people should use a version constraint like `1.31.*`. However publishing that would break all existing projects, not nice.

We could also keep semver if we just published the Docker version as minor, e.g. `2.131` for the second generation of `docker-php/docker-php` with the API version `1.31`. Don't know if that makes sense, I don't have much experience with package maintenance.

**Comment by joelwurtz** [comment]
> When I first found this library I was looking for a "PHP SDK for the Docker API". So I was expecting a "working client library" rather than a toolkit to build it myself.

Certainly, but i have no time actually to handle this unfortunetaly

> Even the latest YAML files from Docker cannot be parsed as expected. So every user would run into problems with that.

These are issues for Jane, where i can have dedicated time at my work to handle it.

> Also there are some specifications missing leading to invalid code that needs to be fixed manually. That shouldn't be the normal case, but it is now.

Also issues for Jane, and there may be thing that we can handle better.

> As a developer I'd have to maintain the client library in my own code repository although it's generated. Doesn't feel nice. Same is true for this project but it's only a single point not every consuming project.

You will have to maintain if you update your docker api version

> Having generated shipped as a SDK feels strange, but together with the additional classes, tests and fixes it makes sense.

> Maybe we could just drop semver (I know, doesn't feel right) and suggest that people should use a version constraint like 1.31.*. However publishing that would break all existing projects, not nice.

It's already not semver, version of this lib follow the docker api version (which is not semver). Problem is for BC break.

In the following weeks, I will look into creating a newest version of docker-php with their own yaml and jane 3.0, so their will be even less maintenance on my side.

I will also commit more documentation to help with contribution in hopes that some people like you submit PR that can be easily merged

**Comment by joelwurtz** [comment]
See https://github.com/docker-php/docker-php/pull/261

**Comment by SamMousa** [comment]
I've been reading up on the issues regarding dependency versions and have some thoughts on libraries using generated code...
As @mburtscher mentioned, most people just want to have an SDK to interact with Docker. For them having all libraries that are used in building the generated classes is not ideal and unnecessary.

I think it would make more sense to split this into 2 repositories, 1 that contains the customization needed and includes the libraries used for generating the code.
The other repository could then contain just the generated code with a much smaller set of dependencies. 
From that point it should be relatively simple to set up some build tool that automatically pushes a new version to the repository with generated files whenever the source repo changes.

While I don't have much time to consistently contribute, I am willing to look into this a bit more to get everything set up.

What do you think of that approach @joelwurtz, @mburtscher?

**Comment by joelwurtz** [comment]
This is exaclty where am i going see #261 :) and https://github.com/docker-php/docker-php-api

Right now you can test this approache by using the 2.0-dev branch of docker -php, there is still some works to do but it should be usable

**Comment by joelwurtz** [comment]
Done :) !
