### ISSUE TITLE
Pull image

### ISSUE THREAD

**Issue by decima** [docker-php/docker-php#253]
Is there a way to pull the image. I work with the docker-php api 1.24 and i read 

http://docker-php.readthedocs.io/en/1.x/image/create/#pull-an-image

but the method does not exists.

**Comment by joelwurtz** [comment]
Look at this method on test : https://github.com/docker-php/docker-php/blob/master/tests/Resource/ContainerResourceTest.php#L25

Basically you use the imageCreate endpoint with a fromImage parameter
