### ISSUE TITLE
Container API errors should still throw exceptions

### ISSUE THREAD

**Issue by Soullivaneuh** [docker-php/docker-php#263]
Concerning this: https://github.com/docker-php/docker-php/blob/cac4840d1d43966a5e0802e24469d806f18e08ac/generated/1.33/Resource/ContainerResource.php#L96-L107

And some others.

Client error should throws exception. This is the goal of exception: to manage not wanted stated. ;-)

Example: https://github.com/KnpLabs/php-github-api/tree/master/lib/Github/Exception

Most of the API sdk work like this. Plus, this permit to have a cleaner end user code, focused on the logic process, then managing exception with a try/catch.

**Comment by Soullivaneuh** [comment]
Another use case: On 1.24 branch, if I want my command to simply fail if the container creation return 500 error code, I have nothing to do because the exception is just raised. Plus, I can manage only some cases of the exception (400, 404...) and throw it away if the error should not be managed.

Here, I'm forced to manage all error and create exception myself.

**Comment by Soullivaneuh** [comment]
Another idea related to #262 why not specify the api version on file generation? No need to worry about which version to handle anymore on we will have only one namespace.

**Comment by joelwurtz** [comment]
It's ok in 2.0, Jane now generate exception for 400 / 500 status code

**Comment by Soullivaneuh** [comment]
> It's ok in 2.0

Well, the issue was telling about the missing exception on 2.0. It is working on 1.24. Did you recently fix this?

**Comment by joelwurtz** [comment]
Don't understand there is no exception on 1.24 ?

**Comment by Soullivaneuh** [comment]
It's ok now, 2.0 throws indeed exception now. Thanks!
