### ISSUE TITLE
How to bind ports range

### ISSUE THREAD

**Issue by ssm2017** [docker-php/docker-php#268]
hello
i am able to create a container and map volume and bind a single port (following the example in the docs).

how to bind a port range like : "10100-10200:10100-10200/udp" ?

**Comment by joelwurtz** [comment]
When creating the container you will use this model : https://github.com/docker-php/docker-php-api/blob/4.1.36/src/Model/ContainersCreatePostBody.php

It have the `exposedPorts` property where you should be able to set it like : 

```
$containerCreate = new ContainersCreatePostBody.php();
$containerCreate->setExposedPorts(new \ArrayObject([
    "10100-10200:10100-10200/udp" => new \stdClass(),
]);
```
