### ISSUE TITLE
Symfony 4 compatibility

### ISSUE THREAD

**Issue by jdecool** [docker-php/docker-php#271]
Hello,

First thanks for this useful library !

I use it on a project I've just migrate in Symfony 4. Actually the library is not compatible with the latest version of the components.

That's why I've make some PR on some dependencies [janephp](https://github.com/janephp/openapi/pull/70) and [symfony-yaml-serializer-encoder-decoder
](https://github.com/fitbug/symfony-yaml-serializer-encoder-decoder/pull/3).

Does it planned to update the `jane/open-api` dependency ?

For now, I can use `docker-php` with Symfony 4 with this `composer.json` : 

```json
{
    "require": {
        "php": "^7.1.3",
        "docker-php/docker-php": "^1.24",
        "symfony/console": "4.0.0 as 3.4.0",
        "symfony/filesystem": "4.0.0 as 3.4.0",
        "symfony/flex": "^1.0",
        "symfony/form": "^4.0",
        "symfony/framework-bundle": "^4.0",
        "symfony/lts": "^4@dev",
        "symfony/orm-pack": "^1.0",
        "symfony/twig-bundle": "^4.0",
        "symfony/yaml": "^4.0"
    },
}
```

**Comment by Soullivaneuh** [comment]
AFAIK, `jane/open-api` should be upgraded on v2.0.

**Comment by joelwurtz** [comment]
Good in 2.0
