### ISSUE TITLE
Network connect/disconnect missing mine type

### ISSUE THREAD

**Issue by Rid** [docker-php/docker-php#274]
The generated NetworkResource.php does not have the `Content-Type` set for `networkConnect` or `networkDisconnect` causing the following error:

`Dec 14 18:00:56 dev-demo dockerd[11262]: time="2017-12-14T18:00:56.827284021Z" level=error msg="Error parsing media type:  error: mime: no media type"`

It looks like an issue with the docker swagger, it's missing:

```yaml
produces:
  - "application/json"
```

from `/networks/{id}/connect` and `/networks/{id}/disconnect`

**Comment by joelwurtz** [comment]
Good in 2.0 : https://github.com/docker-php/docker-php-api/blob/4.1.36/src/Endpoint/NetworkConnect.php
