### ISSUE TITLE
[2.0] Remove CallbackStream::closeAndRead()

### ISSUE THREAD

**Issue by SamMousa** [docker-php/docker-php#277]
The current implementation looks like this:
````
public function closeAndRead()
    {
        $this->stream->close();
        $this->wait();
    }
````

1. Most implementations will clear all internal data when closing the underlying resources.
2. This function is not used in the code.

Can it be removed?

**Comment by SamMousa** [comment]
@joelwurtz bump

**Comment by joelwurtz** [comment]
:+1: go ahead if you want to do a PR (or will do it soon), by the way i'm on http://slack.httplug.io/ if you want to chat over all you issues / pr

**Comment by joelwurtz** [comment]
Done
