### ISSUE TITLE
[2.0] Support multi-stage builds in ContextBuilder

### ISSUE THREAD

**Issue by SamMousa** [docker-php/docker-php#278]
The builder currently doesn't support multi-stage builds.
As far as I can tell all that is needed is to handle `FROM` like any of the other commands that can occur multiple times.

I can make a PR if you agree.

**Comment by joelwurtz** [comment]
go ahead for all stuff in context builder, i don't use it and is present for legacy reason, so if you think of a better api around it for the 2.0 branch will gladly review this.
