### ISSUE TITLE
PHP-CS-Fixer related changes causes bug.

### ISSUE THREAD

**Issue by SamMousa** [docker-php/docker-php#281]
https://github.com/docker-php/docker-php/blob/b511d03f8c0be7f93bd05e8a4b7c64487b3b0537/src/DockerClient.php#L71

Environment variables are always strings so strict comparison will never work.

This is also fixed by my PR #276.
However if that doesn't get merged this should still get fixed.

**Comment by joelwurtz** [comment]
Yes it works if you strict compare to a string or we can cast it to a boolean :)

**Comment by SamMousa** [comment]
Yes, I fixed it by comparing to a string in my forked branch. Will make a separate commit / PR.

**Comment by joelwurtz** [comment]
You can fix it in #276

**Comment by joelwurtz** [comment]
But maybe you mean on the 1.24 branch ?

**Comment by SamMousa** [comment]
No i'm not on 1.24 at all rather skip it and work on and use 2.0 :)

**Comment by joelwurtz** [comment]
Do the 2.0 version works well for you ?

**Comment by SamMousa** [comment]
It works okay; I'm not quite happy with the workflow yet (because the generated code is in a different repo, for example, not sure how to best move forward).

Note that I only use a small subset at this moment (Context stuff and image build).

**Comment by joelwurtz** [comment]
>  I'm not quite happy with the workflow yet (because the generated code is in a different repo, for example, not sure how to best move forward).

I don't think there is a better solution, having this allow to update the higher level of the API for all version of the docker API. Before that a change on this lib would only be on the lastest version, and also it was very hard to break BC, so i think this the best solution for having a better maintenance.

Another option would be to generate the code for the user, but IMO it would make this library way more complex and the benefits are very small.

**Comment by SamMousa** [comment]
> I don't think there is a better solution, having this allow to update the higher level of the API for all version of the docker API. Before that a change on this lib would only be on the lastest version, and also it was very hard to break BC, so i think this the best solution for having a better maintenance.

I agree, I guess it's just me not used to dealing with packages that have generated code.
