### ISSUE TITLE
Building docker image produce php issues

### ISSUE THREAD

**Issue by bainim** [docker-php/docker-php#282]
Hello every one,
I have an issue concerning `php:5.6-apache ,`
My OS: `ubuntu 14.04-server`
this is my `Dockerfile` looks like:

    FROM php:5.6-apache
    MAINTAINER name <name.com>
    LABEL version="1.0"
    LABEL description="Apache 2 / PHP"
    RUN apt-get update -y \
    && apt-get install -y \
        libmcrypt-dev \
        git \
        zip unzip \
        libicu-dev \
        zlib1g-dev \
        php5 \
        php5-fpm \
        php5-pear \
        php5-dev \
        php5-apc \
        php5-common \
        php5-json \
        php5-memcache \
        php5-memcached  \
        php5-xsl \
        php5-mcrypt \
        php5-mysql \
        php5-cli \
        php5-gd \
        php5-intl \
        php5-curl \
    && docker-php-ext-install -j$(nproc) pdo_mysql mysql mysqli iconv mcrypt opcache

This is the error that i have:

     E: Package 'php5' has no installation candidate
     E: Package 'php5-fpm' has no installation candidate
     E: Package 'php-pear' has no installation candidate
     E: Package 'php5-dev' has no installation candidate
     E: Package 'php-apc' has no installation candidate
     E: Package 'php5-common' has no installation candidate
     E: Package 'php5-json' has no installation candidate
     E: Package 'php5-memcache' has no installation candidate
     E: Package 'php5-memcached' has no installation candidate
     E: Package 'php5-xsl' has no installation candidate
     E: Package 'php5-mcrypt' has no installation candidate
     E: Package 'php5-mysql' has no installation candidate
     E: Package 'php5-cli' has no installation candidate
     E: Package 'php5-gd' has no installation candidate
     E: Package 'php5-intl' has no installation candidate
     E: Package 'php5-curl' has no installation candidate

I followed this Link :https://stackoverflow.com/questions/40567133/cannot-add-ppa-ppaondrej-php5-5-6

But there is no result.
Thank you.

**Comment by SamMousa** [comment]
@bainim The error is unrelated to this library.

**Comment by bainim** [comment]
@SamMousa , are you sure about that , this is clalled php-docker so i don't think that your comment is helping in  this situation

**Comment by SamMousa** [comment]
I'm sure.

**Comment by joelwurtz** [comment]
Hey,

@bainim this lib is about having a client to call docker on the REST Api. You problem comes from the official image of php from Docker which is not related to this.

Please report your issue here https://github.com/docker-library/php
