### ISSUE TITLE
Can't pass size parameter on find

### ISSUE THREAD

**Issue by Soullivaneuh** [docker-php/docker-php#286]
According to the API: https://docs.docker.com/engine/api/v1.25/#operation/ContainerInspect

We can pass the `size` query parameter to get the container sizes.

Unfortunately, when I do this:

```php
$this->docker->getContainerManager()->find($containerId, ['size' => 1]),
```

I got this:

```
The option "size" does not exist. Defined options are: ""."
```

Can we fix this on 1.x?

**Comment by joelwurtz** [comment]
Problem is that size appear on 1.25 AFAIK, and current 1.x is done agains 1.24, this should be good when 2.0 is out (by the way it should be close to release)

**Comment by Soullivaneuh** [comment]
Okay in this case, let focus on 2.0 to release it ASAP! :+1:
