### ISSUE TITLE
Bad return type-hint on ImageResourceTrait

### ISSUE THREAD

**Issue by Soullivaneuh** [docker-php/docker-php#290]
On this line: https://github.com/docker-php/docker-php-api/blob/a7781facac54be42d96e91c6c24b86281eaef637/src/Resource/ImageResourceTrait.php#L32

Should be `\Docker\API\Model\ImageSummary[]`, not `\Docker\API\Model\ImageSummary`.

BTW, this issue tracker of `docker-php-api` should be open for this kind of report IMHO.

**Comment by Soullivaneuh** [comment]
The issue seems to concerns all list methods.

Sample:

```php
 * @return \Psr\Http\Message\ResponseInterface|\Docker\API\Model\ContainerSummaryItem
 */
public function containerList(array $parameters = [], string $fetch = self::FETCH_OBJECT)
```

**Comment by joelwurtz** [comment]
It should be good cf : https://github.com/docker-php/docker-php-api/blob/4.1.36/src/Client.php#L37
