### ISSUE TITLE
Status of 2.0-dev

### ISSUE THREAD

**Issue by ryanaslett** [docker-php/docker-php#295]
Just curious if you had a timeline or sense of when 2.0 would stabilize. Is most of the major development done or is there tons of work to do? We'd like to start implementing some things using docker compose, but would like to use a more later version of the docker engine than the 1.24 library supports, so, hoping this is close.

**Comment by Soullivaneuh** [comment]
Please see https://github.com/docker-php/docker-php/pull/261#issuecomment-357448341.

**Comment by joelwurtz** [comment]
Released !

**Comment by ryanaslett** [comment]
awesome.
