### ISSUE TITLE
Doesn't connect to docker sock

### ISSUE THREAD

**Issue by joeyhub** [docker-php/docker-php#303]
"If the DOCKER_HOST environment variable is not set, it will use unix:///var/run/docker.sock as the default tcp address."

inet_pton(): Unrecognized address localhost 

This is because you're using AMP for Async. I recommend replacing it with something that works.

**Comment by joelwurtz** [comment]
Unix socket is working fine on test and the env that i use, can you describe more your problem ?

**Comment by joeyhub** [comment]
Just trying to connect, something as simple as that such as to get events. AMP is messed up with the URI handling. The odd thing is even when I force it to put in the dummy one it fails with invalid URI.

**Comment by trowski** [comment]
@joeyhub Are you using a custom error handler that ignores the current value of `error_reporting()`?

**Comment by joeyhub** [comment]
I did find something with my error_handler screaming. My CR shows it turned off on the 29th. For whatever reason though that I can't remember in the end I just wrote my own generator based async lib and then command library on top of that.
