### ISSUE TITLE
can't bind ports

### ISSUE THREAD

**Issue by calebtr** [docker-php/docker-php#322]
I am trying to open up a single port on the container for the host machine to use. I tried the syntax in #268:

    private function createSeleniumContainer() {
        $docker = Docker::create();
        $containerConfig = new ContainersCreatePostBody();
        $containerConfig->setImage('selenium/hub:3.12.0-americium');
 
        $exposedPorts = new ArrayObject(['4444:4444/tcp' => new \stdClass()]);
 
        $containerConfig->setExposedPorts($exposedPorts);
        return $docker->containerCreate($containerConfig, ['name' => 'selenium-hub']);
    }

After I create the container, docker ps tells me the ports are:

    0/tcp, 4444/tcp  

I am expecting instead:

    0.0.0.0:4444->4444/tcp  

I tried the example in the docs on port-mapping at http://docker-php.readthedocs.io/en/latest/cookbook/container-run/#port-mapping but they appear to be out of date; I got `class PortBinding not found`.

Is my syntax off, or is there something else I can do to open up the port?

**Comment by claytonxia** [comment]
I also don't know how to bind port for the version of 1.24.0, i read the docs but it doesn't cover too much.

**Comment by mohammadreza-soft74** [comment]
in version 2 you can do like this : (127.0.0.1:8484 => 80)
$docker = Docker::Create();
 $containerPortForMap = ['80/tcp' => new \stdClass];
            $port= new \ArrayObject($containerPortForMap);
            $containerConfig->setExposedPorts($port);
            $portBinding = new PortBinding();
            $portBinding->setHostPort('8484');
            $portBinding->setHostIp('0.0.0.0');
            $portMap = new \ArrayObject();
            $portMap['80/tcp'] = [$portBinding];
            $hostConfig = new HostConfig();
            $hostConfig->setPortBindings($portMap);
            $containerConfig->setHostConfig($hostConfig);
            $docker->containerStart($containerConfig);

**Comment by calebtr** [comment]
It looks like the PortBindings class is included in Docker-API 4.1.32 and above. My issue came from using 4.1.29.
