### ISSUE TITLE
Invalid argument supplied for foreach() when running containerInspect

### ISSUE THREAD

**Issue by Coding-Kiwi** [docker-php/docker-php#345]
Error `Invalid argument supplied for foreach()` 
in `vendor/docker-php/docker-php-api/src/Normalizer/NetworkSettingsNormalizer.php` line 60
when running containerInspect

when I run docker inspect in the commandline there is a network listed under "Networks", not sure what's wrong here

**Comment by Coding-Kiwi** [comment]
This might be because my docker api version is too high, will there be any updates on this package?

**Comment by Chakratos** [comment]
Im having the same issue, have you managed to fix it? Im using the latest docker for Ubuntu

**Comment by Coding-Kiwi** [comment]
This might be because you are using a newer version of the docker client. This project is only verified to work with the following api versions as quoted in the readme:

> The test suite currently passes against Docker Remote API v1.25 to v1.36.

try forcing the version in the api:
[Docker API Versioning](https://docs.docker.com/engine/api/v1.37/#section/Versioning)

**Comment by Chakratos** [comment]
> This might be because you are using a newer version of the docker client. This project is only verified to work with the following api versions as quoted in the readme:
> 
> > The test suite currently passes against Docker Remote API v1.25 to v1.36.
> 
> try forcing the version in the api:
> [Docker API Versioning](https://docs.docker.com/engine/api/v1.37/#section/Versioning)

Have you found a way to pass the api version as parameter to the PHP-Docker methods?
I've tried to search for it but couldn't find something
